"""Translation of upstream ``cola/libavoid/tests/restrictedNudging.cpp``.

Auto-generated by ``scripts/translate_upstream.py`` from
``vendor/adaptagrams/cola/libavoid/tests/restrictedNudging.cpp`` at the commit
pinned by ``vendor/adaptagrams``. Regenerate rather than hand-edit.

Pass/fail signal mirrors upstream: exists_orthogonal_touching_paths() must be False.
"""

from libavoid_py import (
    ATTACH_POS_BOTTOM,
    ATTACH_POS_CENTRE,
    ATTACH_POS_LEFT,
    ATTACH_POS_RIGHT,
    ATTACH_POS_TOP,
    CONNECTIONPIN_CENTRE,
    CONNECTIONPIN_UNSET,
    ConnDirFlag,
    ConnEnd,
    ConnRef,
    ConnType,
    JunctionRef,
    Point,
    Polygon,
    Rectangle,
    Router,
    RouterFlag,
    RoutingOption,
    RoutingParameter,
    ShapeConnectionPin,
    ShapeRef,
)


def test_restricted_nudging() -> None:

    router = Router(RouterFlag.PolyLineRouting | RouterFlag.OrthogonalRouting)
    router.set_routing_penalty(RoutingParameter.segmentPenalty, 50)
    router.set_routing_penalty(RoutingParameter.anglePenalty, 0)
    router.set_routing_penalty(RoutingParameter.crossingPenalty, 200)
    router.set_routing_penalty(RoutingParameter.clusterCrossingPenalty, 4000)
    router.set_routing_penalty(RoutingParameter.fixedSharedPathPenalty, 110)
    router.set_routing_parameter(RoutingParameter.idealNudgingDistance, 25)
    poly282634758 = Polygon(4)
    poly282634758.set_point(0, Point(51360, 50215))
    poly282634758.set_point(1, Point(51360, 50460))
    poly282634758.set_point(2, Point(51075, 50460))
    poly282634758.set_point(3, Point(51075, 50215))
    ShapeRef(router, poly282634758, 282634758)
    poly69386928 = Polygon(4)
    poly69386928.set_point(0, Point(51050, 50415))
    poly69386928.set_point(1, Point(51050, 50735))
    poly69386928.set_point(2, Point(50690, 50735))
    poly69386928.set_point(3, Point(50690, 50415))
    ShapeRef(router, poly69386928, 69386928)
    poly11958280 = Polygon(4)
    poly11958280.set_point(0, Point(50460, 50490))
    poly11958280.set_point(1, Point(50460, 50660))
    poly11958280.set_point(2, Point(50290, 50660))
    poly11958280.set_point(3, Point(50290, 50490))
    ShapeRef(router, poly11958280, 11958280)
    poly50591298 = Polygon(4)
    poly50591298.set_point(0, Point(51260, 50015))
    poly50591298.set_point(1, Point(51260, 50185))
    poly50591298.set_point(2, Point(51075, 50185))
    poly50591298.set_point(3, Point(51075, 50015))
    ShapeRef(router, poly50591298, 50591298)
    conn_ref355676284 = ConnRef(router, 355676284)
    src_pt355676284 = ConnEnd(Point(51040, 50575), 8)
    conn_ref355676284.set_source_endpoint(src_pt355676284)
    dst_pt355676284 = ConnEnd(Point(51085, 50300), 4)
    conn_ref355676284.set_dest_endpoint(dst_pt355676284)
    conn_ref355676284.set_routing_type(ConnType.Orthogonal)
    conn_ref33653259 = ConnRef(router, 33653259)
    src_pt33653259 = ConnEnd(Point(51040, 50650), 8)
    conn_ref33653259.set_source_endpoint(src_pt33653259)
    dst_pt33653259 = ConnEnd(Point(51085, 50375), 4)
    conn_ref33653259.set_dest_endpoint(dst_pt33653259)
    conn_ref33653259.set_routing_type(ConnType.Orthogonal)
    conn_ref421608980 = ConnRef(router, 421608980)
    src_pt421608980 = ConnEnd(Point(51040, 50500), 8)
    conn_ref421608980.set_source_endpoint(src_pt421608980)
    dst_pt421608980 = ConnEnd(Point(51085, 50100), 4)
    conn_ref421608980.set_dest_endpoint(dst_pt421608980)
    conn_ref421608980.set_routing_type(ConnType.Orthogonal)
    router.process_transaction()
    overlap = router.exists_orthogonal_touching_paths()

    assert not (overlap)
