"""Translation of upstream ``cola/libavoid/tests/node1.cpp``.

Auto-generated by ``scripts/translate_upstream.py`` from
``vendor/adaptagrams/cola/libavoid/tests/node1.cpp`` at the commit
pinned by ``vendor/adaptagrams``. Regenerate rather than hand-edit.

Pass/fail signal mirrors upstream: process_transaction() must complete without raising.
"""

from libavoid_py import (
    ATTACH_POS_BOTTOM,
    ATTACH_POS_CENTRE,
    ATTACH_POS_LEFT,
    ATTACH_POS_RIGHT,
    ATTACH_POS_TOP,
    CONNECTIONPIN_CENTRE,
    CONNECTIONPIN_UNSET,
    ConnDirFlag,
    ConnEnd,
    ConnRef,
    ConnType,
    JunctionRef,
    Point,
    Polygon,
    Rectangle,
    Router,
    RouterFlag,
    RoutingOption,
    RoutingParameter,
    ShapeConnectionPin,
    ShapeRef,
)


def test_node1() -> None:

    router = Router(RouterFlag.PolyLineRouting | RouterFlag.OrthogonalRouting)
    router.set_routing_penalty(RoutingParameter.segmentPenalty, 50)
    router.set_routing_penalty(RoutingParameter.anglePenalty, 0)
    router.set_routing_penalty(RoutingParameter.crossingPenalty, 200)
    router.set_routing_penalty(RoutingParameter.clusterCrossingPenalty, 4000)
    router.set_routing_parameter(RoutingParameter.idealNudgingDistance, 25)
    buffer = 4
    poly342721632 = Polygon(4)
    poly342721632.set_point(0, Point(51910, 50946))
    poly342721632.set_point(1, Point(51910, 51004))
    poly342721632.set_point(2, Point(51825, 51004))
    poly342721632.set_point(3, Point(51825, 50946))
    shape_ref342721632 = ShapeRef(router, poly342721632, 342721632)
    ShapeConnectionPin(shape_ref342721632, 1, ATTACH_POS_LEFT, ATTACH_POS_CENTRE, True, buffer, ConnDirFlag.ConnDirLeft)
    poly807558175 = Polygon(4)
    poly807558175.set_point(0, Point(51604, 51000))
    poly807558175.set_point(1, Point(51604, 51085))
    poly807558175.set_point(2, Point(51546, 51085))
    poly807558175.set_point(3, Point(51546, 51000))
    shape_ref807558175 = ShapeRef(router, poly807558175, 807558175)
    ShapeConnectionPin(shape_ref807558175, 1, ATTACH_POS_CENTRE, ATTACH_POS_TOP, True, buffer, ConnDirFlag.ConnDirNone)
    poly404900496 = Polygon(4)
    poly404900496.set_point(0, Point(51525, 50946))
    poly404900496.set_point(1, Point(51525, 51004))
    poly404900496.set_point(2, Point(51440, 51004))
    poly404900496.set_point(3, Point(51440, 50946))
    shape_ref404900496 = ShapeRef(router, poly404900496, 404900496)
    ShapeConnectionPin(shape_ref404900496, 1, ATTACH_POS_RIGHT, ATTACH_POS_CENTRE, True, buffer, 8)
    junction_ref265539540 = JunctionRef(router, Point(51625, 50950), 265539540)
    conn_ref985644192 = ConnRef(router, 985644192)
    src_pt985644192 = ConnEnd(shape_ref404900496, 1)
    conn_ref985644192.set_source_endpoint(src_pt985644192)
    dst_pt985644192 = ConnEnd(junction_ref265539540)
    conn_ref985644192.set_dest_endpoint(dst_pt985644192)
    conn_ref985644192.set_routing_type(ConnType.Orthogonal)
    conn_ref467016913 = ConnRef(router, 467016913)
    src_pt467016913 = ConnEnd(junction_ref265539540)
    conn_ref467016913.set_source_endpoint(src_pt467016913)
    dst_pt467016913 = ConnEnd(shape_ref807558175, 1)
    conn_ref467016913.set_dest_endpoint(dst_pt467016913)
    conn_ref467016913.set_routing_type(ConnType.Orthogonal)
    conn_ref45740440 = ConnRef(router, 45740440)
    src_pt45740440 = ConnEnd(shape_ref342721632, 1)
    conn_ref45740440.set_source_endpoint(src_pt45740440)
    dst_pt45740440 = ConnEnd(junction_ref265539540)
    conn_ref45740440.set_dest_endpoint(dst_pt45740440)
    conn_ref45740440.set_routing_type(ConnType.Orthogonal)
    router.process_transaction()
