"""Translation of upstream ``cola/libavoid/tests/inlineoverlap07.cpp``.

Auto-generated by ``scripts/translate_upstream.py`` from
``vendor/adaptagrams/cola/libavoid/tests/inlineoverlap07.cpp`` at the commit
pinned by ``vendor/adaptagrams``. Regenerate rather than hand-edit.

Pass/fail signal mirrors upstream: process_transaction() must complete without raising.
"""

from libavoid_py import (
    ATTACH_POS_BOTTOM,
    ATTACH_POS_CENTRE,
    ATTACH_POS_LEFT,
    ATTACH_POS_RIGHT,
    ATTACH_POS_TOP,
    CONNECTIONPIN_CENTRE,
    CONNECTIONPIN_UNSET,
    ConnDirFlag,
    ConnEnd,
    ConnRef,
    ConnType,
    JunctionRef,
    Point,
    Polygon,
    Rectangle,
    Router,
    RouterFlag,
    RoutingOption,
    RoutingParameter,
    ShapeConnectionPin,
    ShapeRef,
)


def test_inlineoverlap07() -> None:

    router = Router(RouterFlag.PolyLineRouting | RouterFlag.OrthogonalRouting)
    router.set_routing_penalty(RoutingParameter.segmentPenalty, 50)
    router.set_routing_penalty(RoutingParameter.anglePenalty, 0)
    router.set_routing_penalty(RoutingParameter.crossingPenalty, 200)
    router.set_routing_penalty(RoutingParameter.clusterCrossingPenalty, 4000)
    router.set_routing_penalty(RoutingParameter.fixedSharedPathPenalty, 110)
    router.set_routing_penalty(RoutingParameter.portDirectionPenalty, 100)
    router.set_routing_parameter(RoutingParameter.idealNudgingDistance, 25)
    poly186982048 = Polygon(4)
    poly186982048.set_point(0, Point(52660, 50490))
    poly186982048.set_point(1, Point(52660, 50960))
    poly186982048.set_point(2, Point(52100, 50960))
    poly186982048.set_point(3, Point(52100, 50490))
    ShapeRef(router, poly186982048, 186982048)
    poly193989760 = Polygon(4)
    poly193989760.set_point(0, Point(51850, 50665))
    poly193989760.set_point(1, Point(51850, 50835))
    poly193989760.set_point(2, Point(51590, 50835))
    poly193989760.set_point(3, Point(51590, 50665))
    ShapeRef(router, poly193989760, 193989760)
    poly276825384 = Polygon(4)
    poly276825384.set_point(0, Point(51825, 51040))
    poly276825384.set_point(1, Point(51825, 51210))
    poly276825384.set_point(2, Point(51565, 51210))
    poly276825384.set_point(3, Point(51565, 51040))
    ShapeRef(router, poly276825384, 276825384)
    poly190150804 = Polygon(4)
    poly190150804.set_point(0, Point(50460, 51340))
    poly190150804.set_point(1, Point(50460, 51510))
    poly190150804.set_point(2, Point(50290, 51510))
    poly190150804.set_point(3, Point(50290, 51340))
    ShapeRef(router, poly190150804, 190150804)
    conn_ref562170592 = ConnRef(router, 562170592)
    src_pt562170592 = ConnEnd(Point(52110, 50800), 4)
    conn_ref562170592.set_source_endpoint(src_pt562170592)
    dst_pt562170592 = ConnEnd(Point(51815, 51100), 8)
    conn_ref562170592.set_dest_endpoint(dst_pt562170592)
    conn_ref562170592.set_routing_type(ConnType.Orthogonal)
    conn_ref171593006 = ConnRef(router, 171593006)
    src_pt171593006 = ConnEnd(Point(52110, 50750), 4)
    conn_ref171593006.set_source_endpoint(src_pt171593006)
    dst_pt171593006 = ConnEnd(Point(51840, 50725), 8)
    conn_ref171593006.set_dest_endpoint(dst_pt171593006)
    conn_ref171593006.set_routing_type(ConnType.Orthogonal)
    conn_ref172593160 = ConnRef(router, 172593160)
    src_pt172593160 = ConnEnd(Point(51815, 51150), 8)
    conn_ref172593160.set_source_endpoint(src_pt172593160)
    dst_pt172593160 = ConnEnd(Point(52110, 50900), 4)
    conn_ref172593160.set_dest_endpoint(dst_pt172593160)
    conn_ref172593160.set_routing_type(ConnType.Orthogonal)
    conn_ref116944564 = ConnRef(router, 116944564)
    src_pt116944564 = ConnEnd(Point(51840, 50775), 8)
    conn_ref116944564.set_source_endpoint(src_pt116944564)
    dst_pt116944564 = ConnEnd(Point(52110, 50850), 4)
    conn_ref116944564.set_dest_endpoint(dst_pt116944564)
    conn_ref116944564.set_routing_type(ConnType.Orthogonal)
    router.process_transaction()
