"""Translation of upstream ``cola/libavoid/tests/inlineoverlap02.cpp``.

Auto-generated by ``scripts/translate_upstream.py`` from
``vendor/adaptagrams/cola/libavoid/tests/inlineoverlap02.cpp`` at the commit
pinned by ``vendor/adaptagrams``. Regenerate rather than hand-edit.

Pass/fail signal mirrors upstream: exists_orthogonal_fixed_segment_overlap() must be False.
"""

from libavoid_py import (
    ConnDirFlag,
    ConnEnd,
    ConnRef,
    ConnType,
    Point,
    Polygon,
    Rectangle,
    Router,
    RouterFlag,
    RoutingOption,
    RoutingParameter,
    ShapeRef,
)


def test_inlineoverlap02() -> None:

    router = Router(RouterFlag.PolyLineRouting | RouterFlag.OrthogonalRouting)
    router.set_routing_penalty(RoutingParameter.segmentPenalty, 50)
    router.set_routing_penalty(RoutingParameter.anglePenalty, 0)
    router.set_routing_penalty(RoutingParameter.crossingPenalty, 0)
    router.set_routing_penalty(RoutingParameter.clusterCrossingPenalty, 4000)
    router.set_routing_penalty(RoutingParameter.fixedSharedPathPenalty, 110)
    router.set_routing_parameter(RoutingParameter.idealNudgingDistance, 25)
    poly548374163 = Polygon(4)
    poly548374163.set_point(0, Point(52285, 50415))
    poly548374163.set_point(1, Point(52285, 50885))
    poly548374163.set_point(2, Point(51915, 50885))
    poly548374163.set_point(3, Point(51915, 50415))
    ShapeRef(router, poly548374163, 548374163)
    poly942733064 = Polygon(4)
    poly942733064.set_point(0, Point(51829, 50800))
    poly942733064.set_point(1, Point(51829, 50885))
    poly942733064.set_point(2, Point(51771, 50885))
    poly942733064.set_point(3, Point(51771, 50800))
    ShapeRef(router, poly942733064, 942733064)
    poly335855988 = Polygon(4)
    poly335855988.set_point(0, Point(51510, 50190))
    poly335855988.set_point(1, Point(51510, 50885))
    poly335855988.set_point(2, Point(51140, 50885))
    poly335855988.set_point(3, Point(51140, 50190))
    ShapeRef(router, poly335855988, 335855988)
    conn_ref240732432 = ConnRef(router, 240732432)
    src_pt240732432 = ConnEnd(Point(51935, 50650), 4)
    conn_ref240732432.set_source_endpoint(src_pt240732432)
    dst_pt240732432 = ConnEnd(Point(51800, 50810), 1)
    conn_ref240732432.set_dest_endpoint(dst_pt240732432)
    conn_ref240732432.set_routing_type(ConnType.Orthogonal)
    conn_ref148374725 = ConnRef(router, 148374725)
    src_pt148374725 = ConnEnd(Point(51935, 50500), 4)
    conn_ref148374725.set_source_endpoint(src_pt148374725)
    dst_pt148374725 = ConnEnd(Point(51490, 50800), 8)
    conn_ref148374725.set_dest_endpoint(dst_pt148374725)
    conn_ref148374725.set_routing_type(ConnType.Orthogonal)
    conn_ref100850179 = ConnRef(router, 100850179)
    src_pt100850179 = ConnEnd(Point(51935, 50800), 4)
    conn_ref100850179.set_source_endpoint(src_pt100850179)
    dst_pt100850179 = ConnEnd(Point(51490, 50650), 8)
    conn_ref100850179.set_dest_endpoint(dst_pt100850179)
    conn_ref100850179.set_routing_type(ConnType.Orthogonal)
    router.process_transaction()
    overlap = router.exists_orthogonal_fixed_segment_overlap()

    assert not (overlap)
