"""Translation of upstream ``cola/libavoid/tests/inline.cpp``.

Auto-generated by ``scripts/translate_upstream.py`` from
``vendor/adaptagrams/cola/libavoid/tests/inline.cpp`` at the commit
pinned by ``vendor/adaptagrams``. Regenerate rather than hand-edit.

Pass/fail signal mirrors upstream: process_transaction() must complete without raising.
"""

from libavoid_py import (
    ConnDirFlag,
    ConnEnd,
    ConnRef,
    ConnType,
    JunctionRef,
    Point,
    Polygon,
    Rectangle,
    Router,
    RouterFlag,
    RoutingOption,
    RoutingParameter,
    ShapeRef,
)


def test_inline() -> None:

    router = Router(RouterFlag.OrthogonalRouting)
    shape_poly = Rectangle(Point(0, 0), Point(100, 100))
    ShapeRef(router, shape_poly)
    src_pt = ConnEnd(Point(200, 200))
    dst_pt = ConnEnd(Point(95, 25), ConnDirFlag.ConnDirUp | ConnDirFlag.ConnDirRight | ConnDirFlag.ConnDirDown)
    ConnRef(router, src_pt, dst_pt)
    dst_pt = ConnEnd(Point(95, 75), ConnDirFlag.ConnDirUp | ConnDirFlag.ConnDirRight | ConnDirFlag.ConnDirDown)
    ConnRef(router, src_pt, dst_pt)
    dst_pt = ConnEnd(Point(25, 5), ConnDirFlag.ConnDirLeft | ConnDirFlag.ConnDirRight | ConnDirFlag.ConnDirUp)
    ConnRef(router, src_pt, dst_pt)
    dst_pt = ConnEnd(Point(75, 5), ConnDirFlag.ConnDirLeft | ConnDirFlag.ConnDirRight | ConnDirFlag.ConnDirUp)
    ConnRef(router, src_pt, dst_pt)
    dst_pt = ConnEnd(Point(25, 95), ConnDirFlag.ConnDirLeft | ConnDirFlag.ConnDirRight | ConnDirFlag.ConnDirDown)
    ConnRef(router, src_pt, dst_pt)
    dst_pt = ConnEnd(Point(75, 95), ConnDirFlag.ConnDirLeft | ConnDirFlag.ConnDirRight | ConnDirFlag.ConnDirDown)
    ConnRef(router, src_pt, dst_pt)
    router.process_transaction()
