"""Translation of upstream ``cola/libavoid/tests/inlineShapes.cpp``.

Auto-generated by ``scripts/translate_upstream.py`` from
``vendor/adaptagrams/cola/libavoid/tests/inlineShapes.cpp`` at the commit
pinned by ``vendor/adaptagrams``. Regenerate rather than hand-edit.

Pass/fail signal mirrors upstream: process_transaction() must complete without raising.
"""

from libavoid_py import (
    ATTACH_POS_BOTTOM,
    ATTACH_POS_CENTRE,
    ATTACH_POS_LEFT,
    ATTACH_POS_RIGHT,
    ATTACH_POS_TOP,
    CONNECTIONPIN_CENTRE,
    CONNECTIONPIN_UNSET,
    ConnDirFlag,
    ConnEnd,
    ConnRef,
    ConnType,
    JunctionRef,
    Point,
    Polygon,
    Rectangle,
    Router,
    RouterFlag,
    RoutingOption,
    RoutingParameter,
    ShapeConnectionPin,
    ShapeRef,
)


def test_inline_shapes() -> None:

    router = Router(RouterFlag.OrthogonalRouting)
    router.set_routing_penalty(RoutingParameter.segmentPenalty, 50)
    router.set_routing_penalty(RoutingParameter.anglePenalty, 0)
    router.set_routing_penalty(RoutingParameter.crossingPenalty, 0)
    router.set_routing_penalty(RoutingParameter.clusterCrossingPenalty, 4000)
    router.set_routing_penalty(RoutingParameter.fixedSharedPathPenalty, 0)
    poly1 = Polygon(4)
    poly1.set_point(0, Point(52, 188))
    poly1.set_point(1, Point(52, 292))
    poly1.set_point(2, Point(-52, 292))
    poly1.set_point(3, Point(-52, 188))
    shape_ref1 = ShapeRef(router, poly1, 1)
    ShapeConnectionPin(shape_ref1, 544, 0.5, 0.5, True, 10, 0)
    poly2 = Polygon(4)
    poly2.set_point(0, Point(52, -52))
    poly2.set_point(1, Point(52, 52))
    poly2.set_point(2, Point(-52, 52))
    poly2.set_point(3, Point(-52, -52))
    shape_ref2 = ShapeRef(router, poly2, 2)
    ShapeConnectionPin(shape_ref2, 544, 0.5, 0.5, True, 10, 0)
    poly3 = Polygon(4)
    poly3.set_point(0, Point(52, 428))
    poly3.set_point(1, Point(52, 532))
    poly3.set_point(2, Point(-52, 532))
    poly3.set_point(3, Point(-52, 428))
    shape_ref3 = ShapeRef(router, poly3, 3)
    ShapeConnectionPin(shape_ref3, 544, 0.5, 0.5, True, 10, 0)
    poly4 = Polygon(4)
    poly4.set_point(0, Point(52, 68))
    poly4.set_point(1, Point(52, 172))
    poly4.set_point(2, Point(-52, 172))
    poly4.set_point(3, Point(-52, 68))
    shape_ref4 = ShapeRef(router, poly4, 4)
    ShapeConnectionPin(shape_ref4, 544, 0.5, 0.5, True, 10, 0)
    poly5 = Polygon(4)
    poly5.set_point(0, Point(52, 308))
    poly5.set_point(1, Point(52, 412))
    poly5.set_point(2, Point(-52, 412))
    poly5.set_point(3, Point(-52, 308))
    shape_ref5 = ShapeRef(router, poly5, 5)
    ShapeConnectionPin(shape_ref5, 544, 0.5, 0.5, True, 10, 0)
    conn_ref6 = ConnRef(router, 6)
    src_pt6 = ConnEnd(shape_ref2, 544)
    conn_ref6.set_source_endpoint(src_pt6)
    dst_pt6 = ConnEnd(shape_ref5, 544)
    conn_ref6.set_dest_endpoint(dst_pt6)
    conn_ref6.set_routing_type(ConnType.Orthogonal)
    conn_ref7 = ConnRef(router, 7)
    src_pt7 = ConnEnd(shape_ref5, 544)
    conn_ref7.set_source_endpoint(src_pt7)
    dst_pt7 = ConnEnd(shape_ref4, 544)
    conn_ref7.set_dest_endpoint(dst_pt7)
    conn_ref7.set_routing_type(ConnType.Orthogonal)
    conn_ref8 = ConnRef(router, 8)
    src_pt8 = ConnEnd(shape_ref1, 544)
    conn_ref8.set_source_endpoint(src_pt8)
    dst_pt8 = ConnEnd(shape_ref5, 544)
    conn_ref8.set_dest_endpoint(dst_pt8)
    conn_ref8.set_routing_type(ConnType.Orthogonal)
    conn_ref9 = ConnRef(router, 9)
    src_pt9 = ConnEnd(shape_ref2, 544)
    conn_ref9.set_source_endpoint(src_pt9)
    dst_pt9 = ConnEnd(shape_ref3, 544)
    conn_ref9.set_dest_endpoint(dst_pt9)
    conn_ref9.set_routing_type(ConnType.Orthogonal)
    conn_ref10 = ConnRef(router, 10)
    src_pt10 = ConnEnd(shape_ref3, 544)
    conn_ref10.set_source_endpoint(src_pt10)
    dst_pt10 = ConnEnd(shape_ref4, 544)
    conn_ref10.set_dest_endpoint(dst_pt10)
    conn_ref10.set_routing_type(ConnType.Orthogonal)
    conn_ref11 = ConnRef(router, 11)
    src_pt11 = ConnEnd(shape_ref1, 544)
    conn_ref11.set_source_endpoint(src_pt11)
    dst_pt11 = ConnEnd(shape_ref3, 544)
    conn_ref11.set_dest_endpoint(dst_pt11)
    conn_ref11.set_routing_type(ConnType.Orthogonal)
    router.process_transaction()
