"""Translation of upstream ``cola/libavoid/tests/orthordering01.cpp``.

Auto-generated by ``scripts/translate_upstream.py`` from
``vendor/adaptagrams/cola/libavoid/tests/orthordering01.cpp`` at the commit
pinned by ``vendor/adaptagrams``. Regenerate rather than hand-edit.

Pass/fail signal mirrors upstream: exists_crossings() must be 0.
"""

from libavoid_py import (
    ATTACH_POS_BOTTOM,
    ATTACH_POS_CENTRE,
    ATTACH_POS_LEFT,
    ATTACH_POS_RIGHT,
    ATTACH_POS_TOP,
    CONNECTIONPIN_CENTRE,
    CONNECTIONPIN_UNSET,
    ConnDirFlag,
    ConnEnd,
    ConnRef,
    ConnType,
    JunctionRef,
    Point,
    Polygon,
    Rectangle,
    Router,
    RouterFlag,
    RoutingOption,
    RoutingParameter,
    ShapeConnectionPin,
    ShapeRef,
)


def test_orthordering01() -> None:

    router = Router(RouterFlag.PolyLineRouting | RouterFlag.OrthogonalRouting)
    router.set_routing_penalty(RoutingParameter.segmentPenalty, 50)
    router.set_routing_penalty(RoutingParameter.anglePenalty, 0)
    router.set_routing_penalty(RoutingParameter.crossingPenalty, 400)
    router.set_routing_penalty(RoutingParameter.clusterCrossingPenalty, 4000)
    router.set_routing_penalty(RoutingParameter.fixedSharedPathPenalty, 110)
    router.set_routing_parameter(RoutingParameter.idealNudgingDistance, 25)
    poly143407352 = Polygon(4)
    poly143407352.set_point(0, Point(5810, 4340))
    poly143407352.set_point(1, Point(5810, 5035))
    poly143407352.set_point(2, Point(5450, 5035))
    poly143407352.set_point(3, Point(5450, 4340))
    ShapeRef(router, poly143407352, 143407352)
    poly124950386 = Polygon(4)
    poly124950386.set_point(0, Point(4900, 4090))
    poly124950386.set_point(1, Point(4900, 4785))
    poly124950386.set_point(2, Point(4540, 4785))
    poly124950386.set_point(3, Point(4540, 4090))
    ShapeRef(router, poly124950386, 124950386)
    conn_ref373967044 = ConnRef(router, 373967044)
    src_pt373967044 = ConnEnd(Point(4890, 4250), 8)
    conn_ref373967044.set_source_endpoint(src_pt373967044)
    dst_pt373967044 = ConnEnd(Point(5460, 4500), 4)
    conn_ref373967044.set_dest_endpoint(dst_pt373967044)
    conn_ref373967044.set_routing_type(ConnType.Orthogonal)
    conn_ref681881486 = ConnRef(router, 681881486)
    src_pt681881486 = ConnEnd(Point(4890, 4325), 8)
    conn_ref681881486.set_source_endpoint(src_pt681881486)
    dst_pt681881486 = ConnEnd(Point(5460, 4575), 4)
    conn_ref681881486.set_dest_endpoint(dst_pt681881486)
    conn_ref681881486.set_routing_type(ConnType.Orthogonal)
    conn_ref829752 = ConnRef(router, 829752)
    src_pt829752 = ConnEnd(Point(4890, 4400), 8)
    conn_ref829752.set_source_endpoint(src_pt829752)
    dst_pt829752 = ConnEnd(Point(5460, 4650), 4)
    conn_ref829752.set_dest_endpoint(dst_pt829752)
    conn_ref829752.set_routing_type(ConnType.Orthogonal)
    conn_ref17625739 = ConnRef(router, 17625739)
    src_pt17625739 = ConnEnd(Point(4890, 4475), 8)
    conn_ref17625739.set_source_endpoint(src_pt17625739)
    dst_pt17625739 = ConnEnd(Point(5460, 4725), 4)
    conn_ref17625739.set_dest_endpoint(dst_pt17625739)
    conn_ref17625739.set_routing_type(ConnType.Orthogonal)
    conn_ref223864175 = ConnRef(router, 223864175)
    src_pt223864175 = ConnEnd(Point(4890, 4550), 8)
    conn_ref223864175.set_source_endpoint(src_pt223864175)
    dst_pt223864175 = ConnEnd(Point(5460, 4800), 4)
    conn_ref223864175.set_dest_endpoint(dst_pt223864175)
    conn_ref223864175.set_routing_type(ConnType.Orthogonal)
    conn_ref98144280 = ConnRef(router, 98144280)
    src_pt98144280 = ConnEnd(Point(4890, 4625), 8)
    conn_ref98144280.set_source_endpoint(src_pt98144280)
    dst_pt98144280 = ConnEnd(Point(5460, 4875), 4)
    conn_ref98144280.set_dest_endpoint(dst_pt98144280)
    conn_ref98144280.set_routing_type(ConnType.Orthogonal)
    conn_ref283100856 = ConnRef(router, 283100856)
    src_pt283100856 = ConnEnd(Point(4890, 4700), 8)
    conn_ref283100856.set_source_endpoint(src_pt283100856)
    dst_pt283100856 = ConnEnd(Point(5460, 4950), 4)
    conn_ref283100856.set_dest_endpoint(dst_pt283100856)
    conn_ref283100856.set_routing_type(ConnType.Orthogonal)
    conn_ref387080925 = ConnRef(router, 387080925)
    src_pt387080925 = ConnEnd(Point(5460, 4425), 4)
    conn_ref387080925.set_source_endpoint(src_pt387080925)
    dst_pt387080925 = ConnEnd(Point(4890, 4175), 8)
    conn_ref387080925.set_dest_endpoint(dst_pt387080925)
    conn_ref387080925.set_routing_type(ConnType.Orthogonal)
    router.process_transaction()
    crossings = router.exists_crossings()

    assert crossings == 0
