"""Translation of upstream ``cola/libavoid/tests/validPaths02.cpp``.

Auto-generated by ``scripts/translate_upstream.py`` from
``vendor/adaptagrams/cola/libavoid/tests/validPaths02.cpp`` at the commit
pinned by ``vendor/adaptagrams``. Regenerate rather than hand-edit.

Pass/fail signal mirrors upstream: process_transaction() must complete without raising.
"""

from libavoid_py import (
    ATTACH_POS_BOTTOM,
    ATTACH_POS_CENTRE,
    ATTACH_POS_LEFT,
    ATTACH_POS_RIGHT,
    ATTACH_POS_TOP,
    CONNECTIONPIN_CENTRE,
    CONNECTIONPIN_UNSET,
    ConnDirFlag,
    ConnEnd,
    ConnRef,
    ConnType,
    JunctionRef,
    Point,
    Polygon,
    Rectangle,
    Router,
    RouterFlag,
    RoutingOption,
    RoutingParameter,
    ShapeConnectionPin,
    ShapeRef,
)


def test_valid_paths02() -> None:

    router = Router(RouterFlag.PolyLineRouting | RouterFlag.OrthogonalRouting)
    router.set_routing_penalty(RoutingParameter.segmentPenalty, 50)
    router.set_routing_penalty(RoutingParameter.anglePenalty, 0)
    router.set_routing_penalty(RoutingParameter.crossingPenalty, 200)
    router.set_routing_penalty(RoutingParameter.clusterCrossingPenalty, 4000)
    router.set_routing_penalty(RoutingParameter.fixedSharedPathPenalty, 110)
    router.set_routing_penalty(RoutingParameter.portDirectionPenalty, 100)
    router.set_routing_option(RoutingOption.nudgeOrthogonalSegmentsConnectedToShapes, False)
    router.set_routing_option(RoutingOption.improveHyperedgeRoutesMovingJunctions, True)
    router.set_routing_parameter(RoutingParameter.idealNudgingDistance, 25)
    poly186982048 = Polygon(4)
    poly186982048.set_point(0, Point(52660, 50490))
    poly186982048.set_point(1, Point(52660, 50960))
    poly186982048.set_point(2, Point(52090, 50960))
    poly186982048.set_point(3, Point(52090, 50490))
    shape_ref186982048 = ShapeRef(router, poly186982048, 186982048)
    ShapeConnectionPin(shape_ref186982048, 5, 0.982456, 0.12766, True, 0, 8)
    ShapeConnectionPin(shape_ref186982048, 13, 0.982456, 0.234043, True, 0, 8)
    poly197692264 = Polygon(4)
    poly197692264.set_point(0, Point(52560, 50342))
    poly197692264.set_point(1, Point(52560, 50425))
    poly197692264.set_point(2, Point(52440, 50425))
    poly197692264.set_point(3, Point(52440, 50342))
    shape_ref197692264 = ShapeRef(router, poly197692264, 197692264)
    ShapeConnectionPin(shape_ref197692264, 1, 0.5, 0.39759, True, 0, 13)
    ShapeConnectionPin(shape_ref197692264, 2, 0.5, 1, True, 10, 2)
    conn_ref111820287 = ConnRef(router, 111820287)
    src_pt111820287 = ConnEnd(shape_ref186982048, 13)
    conn_ref111820287.set_source_endpoint(src_pt111820287)
    dst_pt111820287 = ConnEnd(shape_ref197692264, 2)
    conn_ref111820287.set_dest_endpoint(dst_pt111820287)
    conn_ref111820287.set_routing_type(ConnType.Orthogonal)
    conn_ref744282799 = ConnRef(router, 744282799)
    src_pt744282799 = ConnEnd(shape_ref186982048, 5)
    conn_ref744282799.set_source_endpoint(src_pt744282799)
    dst_pt744282799 = ConnEnd(shape_ref197692264, 1)
    conn_ref744282799.set_dest_endpoint(dst_pt744282799)
    conn_ref744282799.set_routing_type(ConnType.Orthogonal)
    router.process_transaction()
    result = router.exists_invalid_orthogonal_paths()

    assert not result
