"""Translation of upstream ``cola/libavoid/tests/junction01.cpp``.

Auto-generated by ``scripts/translate_upstream.py`` from
``vendor/adaptagrams/cola/libavoid/tests/junction01.cpp`` at the commit
pinned by ``vendor/adaptagrams``. Regenerate rather than hand-edit.

Pass/fail signal mirrors upstream: process_transaction() must complete without raising.
"""

from libavoid_py import (
    ATTACH_POS_BOTTOM,
    ATTACH_POS_CENTRE,
    ATTACH_POS_LEFT,
    ATTACH_POS_RIGHT,
    ATTACH_POS_TOP,
    CONNECTIONPIN_CENTRE,
    CONNECTIONPIN_UNSET,
    ConnDirFlag,
    ConnEnd,
    ConnRef,
    ConnType,
    JunctionRef,
    Point,
    Polygon,
    Rectangle,
    Router,
    RouterFlag,
    RoutingOption,
    RoutingParameter,
    ShapeConnectionPin,
    ShapeRef,
)


def test_junction01() -> None:

    router = Router(RouterFlag.OrthogonalRouting)
    router.set_routing_penalty(RoutingParameter.segmentPenalty, 50)
    router.set_routing_penalty(RoutingParameter.anglePenalty, 0)
    router.set_routing_penalty(RoutingParameter.crossingPenalty, 0)
    router.set_routing_penalty(RoutingParameter.clusterCrossingPenalty, 4000)
    router.set_routing_penalty(RoutingParameter.fixedSharedPathPenalty, 105)
    router.set_routing_parameter(RoutingParameter.idealNudgingDistance, 25)
    rect478845150 = Rectangle(Point(50695, 51070), Point(50705, 51080))
    shape_ref478845150 = ShapeRef(router, rect478845150, 478845150)
    pin = ShapeConnectionPin(shape_ref478845150, CONNECTIONPIN_CENTRE, ATTACH_POS_CENTRE, ATTACH_POS_CENTRE, True, 0.0, ConnDirFlag.ConnDirNone)
    pin.exclusive = False
    rect92712048 = Rectangle(Point(51246, 50475), Point(51304, 50585))
    ShapeRef(router, rect92712048, 92712048)
    rect23127921 = Rectangle(Point(50365, 50766), Point(50485, 50834))
    ShapeRef(router, rect23127921, 23127921)
    rect159957148 = Rectangle(Point(51740, 50891), Point(51860, 50959))
    ShapeRef(router, rect159957148, 159957148)
    rect1350214 = Rectangle(Point(50375, 51015), Point(50625, 51135))
    ShapeRef(router, rect1350214, 1350214)
    rect247197258 = Rectangle(Point(50265, 51046), Point(50375, 51104))
    ShapeRef(router, rect247197258, 247197258)
    rect281096654 = Rectangle(Point(50700, 50390), Point(51000, 50610))
    ShapeRef(router, rect281096654, 281096654)
    src_pt342420237 = ConnEnd(Point(50425, 50800), 15)
    dst_pt342420237 = ConnEnd(Point(50710, 50450), 4)
    ConnRef(router, src_pt342420237, dst_pt342420237, 342420237)
    src_pt352019675 = ConnEnd(Point(50990, 50500), 8)
    dst_pt352019675 = ConnEnd(shape_ref478845150, CONNECTIONPIN_CENTRE)
    ConnRef(router, src_pt352019675, dst_pt352019675, 352019675)
    src_pt42699400 = ConnEnd(shape_ref478845150, CONNECTIONPIN_CENTRE)
    dst_pt42699400 = ConnEnd(Point(50615, 51075), 8)
    ConnRef(router, src_pt42699400, dst_pt42699400, 42699400)
    src_pt94712625 = ConnEnd(Point(50710, 50550), 4)
    dst_pt94712625 = ConnEnd(shape_ref478845150, CONNECTIONPIN_CENTRE)
    ConnRef(router, src_pt94712625, dst_pt94712625, 94712625)
    src_pt92802970 = ConnEnd(Point(50990, 50450), 8)
    dst_pt92802970 = ConnEnd(Point(51275, 50485), 1)
    ConnRef(router, src_pt92802970, dst_pt92802970, 92802970)
    src_pt716502036 = ConnEnd(Point(50710, 50500), 4)
    dst_pt716502036 = ConnEnd(Point(51800, 50925), 15)
    ConnRef(router, src_pt716502036, dst_pt716502036, 716502036)
    router.process_transaction()
