"""Translation of upstream ``cola/libavoid/tests/inlineoverlap03.cpp``.

Auto-generated by ``scripts/translate_upstream.py`` from
``vendor/adaptagrams/cola/libavoid/tests/inlineoverlap03.cpp`` at the commit
pinned by ``vendor/adaptagrams``. Regenerate rather than hand-edit.

Pass/fail signal mirrors upstream: exists_orthogonal_fixed_segment_overlap() must be False.
"""

from libavoid_py import (
    ATTACH_POS_BOTTOM,
    ATTACH_POS_CENTRE,
    ATTACH_POS_LEFT,
    ATTACH_POS_RIGHT,
    ATTACH_POS_TOP,
    CONNECTIONPIN_CENTRE,
    CONNECTIONPIN_UNSET,
    ConnDirFlag,
    ConnEnd,
    ConnRef,
    ConnType,
    JunctionRef,
    Point,
    Polygon,
    Rectangle,
    Router,
    RouterFlag,
    RoutingOption,
    RoutingParameter,
    ShapeConnectionPin,
    ShapeRef,
)


def test_inlineoverlap03() -> None:

    router = Router(RouterFlag.PolyLineRouting | RouterFlag.OrthogonalRouting)
    router.set_routing_penalty(RoutingParameter.segmentPenalty, 50)
    router.set_routing_penalty(RoutingParameter.anglePenalty, 0)
    router.set_routing_penalty(RoutingParameter.crossingPenalty, 0)
    router.set_routing_penalty(RoutingParameter.clusterCrossingPenalty, 4000)
    router.set_routing_penalty(RoutingParameter.fixedSharedPathPenalty, 110)
    router.set_routing_parameter(RoutingParameter.idealNudgingDistance, 25)
    poly421433292 = Polygon(4)
    poly421433292.set_point(0, Point(51335, 50215))
    poly421433292.set_point(1, Point(51335, 50385))
    poly421433292.set_point(2, Point(51065, 50385))
    poly421433292.set_point(3, Point(51065, 50215))
    ShapeRef(router, poly421433292, 421433292)
    poly174734866 = Polygon(4)
    poly174734866.set_point(0, Point(51335, 50490))
    poly174734866.set_point(1, Point(51335, 50660))
    poly174734866.set_point(2, Point(51065, 50660))
    poly174734866.set_point(3, Point(51065, 50490))
    ShapeRef(router, poly174734866, 174734866)
    poly564884274 = Polygon(4)
    poly564884274.set_point(0, Point(50635, 50500))
    poly564884274.set_point(1, Point(50635, 50583))
    poly564884274.set_point(2, Point(50515, 50583))
    poly564884274.set_point(3, Point(50515, 50500))
    ShapeRef(router, poly564884274, 564884274)
    conn_ref103176525 = ConnRef(router, 103176525)
    src_pt103176525 = ConnEnd(Point(51085, 50550), 4)
    conn_ref103176525.set_source_endpoint(src_pt103176525)
    dst_pt103176525 = ConnEnd(Point(50575, 50510), 1)
    conn_ref103176525.set_dest_endpoint(dst_pt103176525)
    conn_ref103176525.set_routing_type(ConnType.Orthogonal)
    conn_ref223495632 = ConnRef(router, 223495632)
    src_pt223495632 = ConnEnd(Point(51085, 50325), 4)
    conn_ref223495632.set_source_endpoint(src_pt223495632)
    dst_pt223495632 = ConnEnd(Point(50575, 50550), 14)
    conn_ref223495632.set_dest_endpoint(dst_pt223495632)
    conn_ref223495632.set_routing_type(ConnType.Orthogonal)
    router.process_transaction()
    overlap = router.exists_orthogonal_fixed_segment_overlap()

    assert not (overlap)
