"""Translation of upstream ``cola/libavoid/tests/infinity.cpp``.

Auto-generated by ``scripts/translate_upstream.py`` from
``vendor/adaptagrams/cola/libavoid/tests/infinity.cpp`` at the commit
pinned by ``vendor/adaptagrams``. Regenerate rather than hand-edit.

Pass/fail signal mirrors upstream: process_transaction() must complete without raising.
"""

from libavoid_py import (
    ConnDirFlag,
    ConnEnd,
    ConnRef,
    ConnType,
    JunctionRef,
    Point,
    Polygon,
    Rectangle,
    Router,
    RouterFlag,
    RoutingOption,
    RoutingParameter,
    ShapeRef,
)


def test_infinity() -> None:

    router = Router(RouterFlag.OrthogonalRouting)
    router.set_routing_penalty(RoutingParameter.segmentPenalty, 50)
    router.set_routing_parameter(RoutingParameter.idealNudgingDistance, 10)
    rect47 = Rectangle(Point(51145, 50195), Point(51145+360, 50195+685))
    ShapeRef(router, rect47)
    rect46 = Rectangle(Point(51920, 49770), Point(51920+360, 49770+310))
    ShapeRef(router, rect46)
    rect45 = Rectangle(Point(51151, 49770), Point(51151+360, 49770+310))
    ShapeRef(router, rect45)
    src_pt53 = ConnEnd(Point(51150,49850), 4)
    dst_pt53 = ConnEnd(Point(51500,50350), 8)
    ConnRef(router, src_pt53, dst_pt53)
    src_pt52 = ConnEnd(Point(52275,49850), 8)
    dst_pt52 = ConnEnd(Point(51150,49925), 4)
    ConnRef(router, src_pt52, dst_pt52)
    src_pt6 = ConnEnd(Point(51150,50500), 4)
    dst_pt6 = ConnEnd(Point(51925,50000), 4)
    ConnRef(router, src_pt6, dst_pt6, 6)
    router.process_transaction()
