"""Translation of upstream ``cola/libavoid/tests/inlineoverlap05.cpp``.

Auto-generated by ``scripts/translate_upstream.py`` from
``vendor/adaptagrams/cola/libavoid/tests/inlineoverlap05.cpp`` at the commit
pinned by ``vendor/adaptagrams``. Regenerate rather than hand-edit.

Pass/fail signal mirrors upstream: exists_orthogonal_fixed_segment_overlap() must be False.
"""

from libavoid_py import (
    ConnDirFlag,
    ConnEnd,
    ConnRef,
    ConnType,
    JunctionRef,
    Point,
    Polygon,
    Rectangle,
    Router,
    RouterFlag,
    RoutingOption,
    RoutingParameter,
    ShapeRef,
)


def test_inlineoverlap05() -> None:

    router = Router(RouterFlag.PolyLineRouting | RouterFlag.OrthogonalRouting)
    router.set_routing_penalty(RoutingParameter.segmentPenalty, 50)
    router.set_routing_penalty(RoutingParameter.anglePenalty, 0)
    router.set_routing_penalty(RoutingParameter.crossingPenalty, 0)
    router.set_routing_penalty(RoutingParameter.clusterCrossingPenalty, 4000)
    router.set_routing_penalty(RoutingParameter.fixedSharedPathPenalty, 110)
    router.set_routing_parameter(RoutingParameter.idealNudgingDistance, 25)
    poly231469760 = Polygon(4)
    poly231469760.set_point(0, Point(6385, 9390))
    poly231469760.set_point(1, Point(6385, 9560))
    poly231469760.set_point(2, Point(6200, 9560))
    poly231469760.set_point(3, Point(6200, 9390))
    ShapeRef(router, poly231469760, 231469760)
    poly7136376 = Polygon(4)
    poly7136376.set_point(0, Point(6560, 9290))
    poly7136376.set_point(1, Point(6560, 9460))
    poly7136376.set_point(2, Point(6375, 9460))
    poly7136376.set_point(3, Point(6375, 9290))
    ShapeRef(router, poly7136376, 7136376)
    poly215821749 = Polygon(4)
    poly215821749.set_point(0, Point(6510, 9540))
    poly215821749.set_point(1, Point(6510, 9710))
    poly215821749.set_point(2, Point(6325, 9710))
    poly215821749.set_point(3, Point(6325, 9540))
    ShapeRef(router, poly215821749, 215821749)
    poly83086994 = Polygon(4)
    poly83086994.set_point(0, Point(5925, 9240))
    poly83086994.set_point(1, Point(5925, 10085))
    poly83086994.set_point(2, Point(5575, 10085))
    poly83086994.set_point(3, Point(5575, 9240))
    ShapeRef(router, poly83086994, 83086994)
    conn_ref292408794 = ConnRef(router, 292408794)
    src_pt292408794 = ConnEnd(Point(5915, 9625), 8)
    conn_ref292408794.set_source_endpoint(src_pt292408794)
    dst_pt292408794 = ConnEnd(Point(6210, 9475), 4)
    conn_ref292408794.set_dest_endpoint(dst_pt292408794)
    conn_ref292408794.set_routing_type(ConnType.Orthogonal)
    conn_ref40917776 = ConnRef(router, 40917776)
    src_pt40917776 = ConnEnd(Point(5915, 9550), 8)
    conn_ref40917776.set_source_endpoint(src_pt40917776)
    dst_pt40917776 = ConnEnd(Point(6385, 9375), 4)
    conn_ref40917776.set_dest_endpoint(dst_pt40917776)
    conn_ref40917776.set_routing_type(ConnType.Orthogonal)
    conn_ref629564142 = ConnRef(router, 629564142)
    src_pt629564142 = ConnEnd(Point(5915, 9475), 8)
    conn_ref629564142.set_source_endpoint(src_pt629564142)
    dst_pt629564142 = ConnEnd(Point(6335, 9625), 4)
    conn_ref629564142.set_dest_endpoint(dst_pt629564142)
    conn_ref629564142.set_routing_type(ConnType.Orthogonal)
    router.process_transaction()
    overlap = router.exists_orthogonal_fixed_segment_overlap()

    assert not (overlap)
