"""Translation of upstream ``cola/libavoid/tests/connectionpin01.cpp``.

Auto-generated by ``scripts/translate_upstream.py`` from
``vendor/adaptagrams/cola/libavoid/tests/connectionpin01.cpp`` at the commit
pinned by ``vendor/adaptagrams``. Regenerate rather than hand-edit.

Pass/fail signal mirrors upstream: process_transaction() must complete without raising.
"""

from libavoid_py import (
    ATTACH_POS_BOTTOM,
    ATTACH_POS_CENTRE,
    ATTACH_POS_LEFT,
    ATTACH_POS_RIGHT,
    ATTACH_POS_TOP,
    CONNECTIONPIN_CENTRE,
    CONNECTIONPIN_UNSET,
    ConnDirFlag,
    ConnEnd,
    ConnRef,
    ConnType,
    JunctionRef,
    Point,
    Polygon,
    Rectangle,
    Router,
    RouterFlag,
    RoutingOption,
    RoutingParameter,
    ShapeConnectionPin,
    ShapeRef,
)


def test_connectionpin01() -> None:

    router = Router(RouterFlag.OrthogonalRouting)
    shape_rect1 = Rectangle(Point(0, 0), Point(10, 10))
    shape_ref1 = ShapeRef(router, shape_rect1)
    shape_rect2 = Rectangle(Point(40, 20), Point(50, 30))
    shape_ref2 = ShapeRef(router, shape_rect2)
    CENTRE = 1
    ShapeConnectionPin(shape_ref1, CENTRE, ATTACH_POS_CENTRE, ATTACH_POS_CENTRE, True, 0.0, ConnDirFlag.ConnDirNone)
    ShapeConnectionPin(shape_ref2, CENTRE, ATTACH_POS_CENTRE, ATTACH_POS_CENTRE, True, 0.0, ConnDirFlag.ConnDirNone)
    dst_end = ConnEnd(shape_ref1, CENTRE)
    src_end = ConnEnd(shape_ref2, CENTRE)
    ConnRef(router, src_end, dst_end)
    router.process_transaction()
    router.move_shape(shape_ref2, 5, 0)
    router.process_transaction()
    router.move_shape(shape_ref1, 0, -10)
    router.process_transaction()
