"""Translation of upstream ``cola/libavoid/tests/inlineoverlap01.cpp``.

Auto-generated by ``scripts/translate_upstream.py`` from
``vendor/adaptagrams/cola/libavoid/tests/inlineoverlap01.cpp`` at the commit
pinned by ``vendor/adaptagrams``. Regenerate rather than hand-edit.

Pass/fail signal mirrors upstream: exists_orthogonal_touching_paths() must be False.
"""

from libavoid_py import (
    ConnDirFlag,
    ConnEnd,
    ConnRef,
    ConnType,
    JunctionRef,
    Point,
    Polygon,
    Rectangle,
    Router,
    RouterFlag,
    RoutingOption,
    RoutingParameter,
    ShapeRef,
)


def test_inlineoverlap01() -> None:

    router = Router(RouterFlag.OrthogonalRouting)
    router.set_routing_penalty(RoutingParameter.segmentPenalty)
    router.set_routing_penalty(RoutingParameter.fixedSharedPathPenalty)
    router.set_routing_parameter(RoutingParameter.idealNudgingDistance, 20)
    rect335855988 = Rectangle(Point(51140, 50190), Point(51510, 50885))
    ShapeRef(router, rect335855988, 335855988)
    rect548374163 = Rectangle(Point(51915, 50415), Point(52285, 50885))
    ShapeRef(router, rect548374163, 548374163)
    rect942733064 = Rectangle(Point(51771, 50790), Point(51829, 50885))
    ShapeRef(router, rect942733064, 942733064)
    src_pt100850179 = ConnEnd(Point(51925, 50800), 4)
    dst_pt100850179 = ConnEnd(Point(51500, 50650), 8)
    ConnRef(router, src_pt100850179, dst_pt100850179, 100850179)
    src_pt240732432 = ConnEnd(Point(51925, 50650), 4)
    dst_pt240732432 = ConnEnd(Point(51800, 50800), 1)
    ConnRef(router, src_pt240732432, dst_pt240732432, 240732432)
    router.process_transaction()
    overlap = router.exists_orthogonal_touching_paths()

    assert not (overlap)
