"""Translation of upstream ``cola/libavoid/tests/nudgeintobug.cpp``.

Auto-generated by ``scripts/translate_upstream.py`` from
``vendor/adaptagrams/cola/libavoid/tests/nudgeintobug.cpp`` at the commit
pinned by ``vendor/adaptagrams``. Regenerate rather than hand-edit.

Pass/fail signal mirrors upstream: exists_orthogonal_fixed_segment_overlap() must be False.
"""

from libavoid_py import (
    ConnDirFlag,
    ConnEnd,
    ConnRef,
    ConnType,
    JunctionRef,
    Point,
    Polygon,
    Rectangle,
    Router,
    RouterFlag,
    RoutingOption,
    RoutingParameter,
    ShapeRef,
)


def test_nudgeintobug() -> None:

    router = Router(RouterFlag.OrthogonalRouting)
    router.set_routing_penalty(RoutingParameter.segmentPenalty, 50)
    router.set_routing_penalty(RoutingParameter.anglePenalty, 0)
    router.set_routing_penalty(RoutingParameter.crossingPenalty, 200)
    router.set_routing_penalty(RoutingParameter.clusterCrossingPenalty, 4000)
    router.set_routing_penalty(RoutingParameter.fixedSharedPathPenalty, 110)
    router.set_routing_parameter(RoutingParameter.idealNudgingDistance, 25)
    rect548374163 = Rectangle(Point(51900, 50400), Point(52300, 50900))
    ShapeRef(router, rect548374163, 548374163)
    rect901116812 = Rectangle(Point(51131, 49750), Point(51531, 50100))
    ShapeRef(router, rect901116812, 901116812)
    rect335855988 = Rectangle(Point(51125, 50175), Point(51525, 50900))
    ShapeRef(router, rect335855988, 335855988)
    rect448725420 = Rectangle(Point(52375, 50750), Point(52575, 50900))
    ShapeRef(router, rect448725420, 448725420)
    rect74263573 = Rectangle(Point(51900, 49750), Point(52300, 50100))
    ShapeRef(router, rect74263573, 74263573)
    src_pt463223880 = ConnEnd(Point(51500, 50275), 8)
    dst_pt463223880 = ConnEnd(Point(51150, 50275), 4)
    src_pt144520410 = ConnEnd(Point(51150, 49850), 4)
    dst_pt144520410 = ConnEnd(Point(51500, 50350), 8)
    src_pt45398340 = ConnEnd(Point(52400, 50825), 4)
    dst_pt45398340 = ConnEnd(Point(51500, 49925), 8)
    src_pt29344262 = ConnEnd(Point(51150, 50500), 4)
    dst_pt29344262 = ConnEnd(Point(51925, 50000), 4)
    ConnRef(router, src_pt29344262, dst_pt29344262, 29344262)
    ConnRef(router, src_pt45398340, dst_pt45398340, 45398340)
    ConnRef(router, src_pt144520410, dst_pt144520410, 144520410)
    ConnRef(router, src_pt463223880, dst_pt463223880, 463223880)
    router.process_transaction()
    overlap = router.exists_orthogonal_fixed_segment_overlap()
    touching = router.exists_orthogonal_touching_paths()

    assert not (overlap or touching)
