"""Translation of upstream ``cola/libavoid/tests/finalSegmentNudging1.cpp``.

Auto-generated by ``scripts/translate_upstream.py`` from
``vendor/adaptagrams/cola/libavoid/tests/finalSegmentNudging1.cpp`` at the commit
pinned by ``vendor/adaptagrams``. Regenerate rather than hand-edit.

Pass/fail signal mirrors upstream: exists_crossings() must be 0.
"""

from libavoid_py import (
    ConnDirFlag,
    ConnEnd,
    ConnRef,
    ConnType,
    JunctionRef,
    Point,
    Polygon,
    Rectangle,
    Router,
    RouterFlag,
    RoutingOption,
    RoutingParameter,
    ShapeRef,
)


def test_final_segment_nudging1() -> None:

    router = Router(RouterFlag.PolyLineRouting | RouterFlag.OrthogonalRouting)
    router.set_routing_penalty(RoutingParameter.segmentPenalty, 50)
    router.set_routing_penalty(RoutingParameter.anglePenalty, 0)
    router.set_routing_penalty(RoutingParameter.crossingPenalty, 0)
    router.set_routing_penalty(RoutingParameter.clusterCrossingPenalty, 4000)
    router.set_routing_penalty(RoutingParameter.fixedSharedPathPenalty, 0)
    router.set_routing_penalty(RoutingParameter.portDirectionPenalty, 100)
    router.set_routing_option(RoutingOption.nudgeOrthogonalSegmentsConnectedToShapes, True)
    router.set_routing_option(RoutingOption.improveHyperedgeRoutesMovingJunctions, True)
    router.set_routing_option(RoutingOption.penaliseOrthogonalSharedPathsAtConnEnds, False)
    poly12 = Polygon(4)
    poly12.set_point(0, Point(2072.79, 1841.95))
    poly12.set_point(1, Point(2072.79, 1903.95))
    poly12.set_point(2, Point(2010.79, 1903.95))
    poly12.set_point(3, Point(2010.79, 1841.95))
    ShapeRef(router, poly12, 12)
    poly13 = Polygon(4)
    poly13.set_point(0, Point(2272.79, 1841.95))
    poly13.set_point(1, Point(2272.79, 1903.95))
    poly13.set_point(2, Point(2210.79, 1903.95))
    poly13.set_point(3, Point(2210.79, 1841.95))
    ShapeRef(router, poly13, 13)
    poly96 = Polygon(4)
    poly96.set_point(0, Point(2187.79, 1862.95))
    poly96.set_point(1, Point(2187.79, 1882.95))
    poly96.set_point(2, Point(2155.79, 1882.95))
    poly96.set_point(3, Point(2155.79, 1862.95))
    ShapeRef(router, poly96, 96)
    poly97 = Polygon(4)
    poly97.set_point(0, Point(2139.79, 1864.95))
    poly97.set_point(1, Point(2139.79, 1904.95))
    poly97.set_point(2, Point(2063.79, 1904.95))
    poly97.set_point(3, Point(2063.79, 1864.95))
    ShapeRef(router, poly97, 97)
    poly250 = Polygon(4)
    poly250.set_point(0, Point(2199.79, 1802.95))
    poly250.set_point(1, Point(2199.79, 1862.95))
    poly250.set_point(2, Point(2143.79, 1862.95))
    poly250.set_point(3, Point(2143.79, 1802.95))
    ShapeRef(router, poly250, 250)
    conn_ref416 = ConnRef(router, 416)
    src_pt416 = ConnEnd(Point(2041.79, 1872.95), 15)
    conn_ref416.set_source_endpoint(src_pt416)
    dst_pt416 = ConnEnd(Point(2156.79, 1872.95), 4)
    conn_ref416.set_dest_endpoint(dst_pt416)
    conn_ref416.set_routing_type(ConnType.Orthogonal)
    conn_ref531 = ConnRef(router, 531)
    src_pt531 = ConnEnd(Point(2186.79, 1872.95), 8)
    conn_ref531.set_source_endpoint(src_pt531)
    dst_pt531 = ConnEnd(Point(2241.79, 1872.95), 15)
    conn_ref531.set_dest_endpoint(dst_pt531)
    conn_ref531.set_routing_type(ConnType.Orthogonal)
    conn_ref726 = ConnRef(router, 726)
    src_pt726 = ConnEnd(Point(2111.79, 1884.95), 15)
    conn_ref726.set_source_endpoint(src_pt726)
    dst_pt726 = ConnEnd(Point(2241.79, 1872.95), 15)
    conn_ref726.set_dest_endpoint(dst_pt726)
    conn_ref726.set_routing_type(ConnType.Orthogonal)
    router.process_transaction()
    optimised_for_connector_type = True
    crossings = router.exists_crossings(optimised_for_connector_type)

    assert crossings == 0
