"""Translation of upstream ``cola/libavoid/tests/inlineoverlap04.cpp``.

Auto-generated by ``scripts/translate_upstream.py`` from
``vendor/adaptagrams/cola/libavoid/tests/inlineoverlap04.cpp`` at the commit
pinned by ``vendor/adaptagrams``. Regenerate rather than hand-edit.

Pass/fail signal mirrors upstream: exists_orthogonal_fixed_segment_overlap() must be False.
"""

from libavoid_py import (
    ConnDirFlag,
    ConnEnd,
    ConnRef,
    ConnType,
    JunctionRef,
    Point,
    Polygon,
    Rectangle,
    Router,
    RouterFlag,
    RoutingOption,
    RoutingParameter,
    ShapeRef,
)


def test_inlineoverlap04() -> None:

    router = Router(RouterFlag.PolyLineRouting | RouterFlag.OrthogonalRouting)
    router.set_routing_penalty(RoutingParameter.segmentPenalty, 50)
    router.set_routing_penalty(RoutingParameter.anglePenalty, 0)
    router.set_routing_penalty(RoutingParameter.crossingPenalty, 0)
    router.set_routing_penalty(RoutingParameter.clusterCrossingPenalty, 4000)
    router.set_routing_penalty(RoutingParameter.fixedSharedPathPenalty, 110)
    router.set_routing_parameter(RoutingParameter.idealNudgingDistance, 25)
    poly170253204 = Polygon(4)
    poly170253204.set_point(0, Point(50450, 50190))
    poly170253204.set_point(1, Point(50450, 50360))
    poly170253204.set_point(2, Point(50265, 50360))
    poly170253204.set_point(3, Point(50265, 50190))
    ShapeRef(router, poly170253204, 170253204)
    poly914700248 = Polygon(4)
    poly914700248.set_point(0, Point(50800, 50390))
    poly914700248.set_point(1, Point(50800, 50560))
    poly914700248.set_point(2, Point(50615, 50560))
    poly914700248.set_point(3, Point(50615, 50390))
    ShapeRef(router, poly914700248, 914700248)
    poly285103539 = Polygon(4)
    poly285103539.set_point(0, Point(51385, 50390))
    poly285103539.set_point(1, Point(51385, 50560))
    poly285103539.set_point(2, Point(51200, 50560))
    poly285103539.set_point(3, Point(51200, 50390))
    ShapeRef(router, poly285103539, 285103539)
    poly252459412 = Polygon(4)
    poly252459412.set_point(0, Point(51360, 50190))
    poly252459412.set_point(1, Point(51360, 50360))
    poly252459412.set_point(2, Point(51175, 50360))
    poly252459412.set_point(3, Point(51175, 50190))
    ShapeRef(router, poly252459412, 252459412)
    conn_ref573390636 = ConnRef(router, 573390636)
    src_pt573390636 = ConnEnd(Point(50790, 50475), 8)
    conn_ref573390636.set_source_endpoint(src_pt573390636)
    dst_pt573390636 = ConnEnd(Point(51185, 50275), 4)
    conn_ref573390636.set_dest_endpoint(dst_pt573390636)
    conn_ref573390636.set_routing_type(ConnType.Orthogonal)
    conn_ref214207623 = ConnRef(router, 214207623)
    src_pt214207623 = ConnEnd(Point(51210, 50475), 4)
    conn_ref214207623.set_source_endpoint(src_pt214207623)
    dst_pt214207623 = ConnEnd(Point(50440, 50275), 8)
    conn_ref214207623.set_dest_endpoint(dst_pt214207623)
    conn_ref214207623.set_routing_type(ConnType.Orthogonal)
    router.process_transaction()
    overlap = router.exists_orthogonal_fixed_segment_overlap()

    assert not (overlap)
