"""Translation of upstream ``cola/libavoid/tests/inlineoverlap08.cpp``.

Auto-generated by ``scripts/translate_upstream.py`` from
``vendor/adaptagrams/cola/libavoid/tests/inlineoverlap08.cpp`` at the commit
pinned by ``vendor/adaptagrams``. Regenerate rather than hand-edit.

Pass/fail signal mirrors upstream: exists_orthogonal_fixed_segment_overlap() must be False.
"""

from libavoid_py import (
    ConnDirFlag,
    ConnEnd,
    ConnRef,
    ConnType,
    Point,
    Polygon,
    Rectangle,
    Router,
    RouterFlag,
    RoutingOption,
    RoutingParameter,
    ShapeRef,
)


def test_inlineoverlap08() -> None:

    router = Router(RouterFlag.PolyLineRouting | RouterFlag.OrthogonalRouting)
    router.set_routing_parameter(RoutingParameter.segmentPenalty, 10)
    router.set_routing_parameter(RoutingParameter.anglePenalty, 0)
    router.set_routing_parameter(RoutingParameter.crossingPenalty, 0)
    router.set_routing_parameter(RoutingParameter.clusterCrossingPenalty, 4000)
    router.set_routing_parameter(RoutingParameter.fixedSharedPathPenalty, 400)
    router.set_routing_parameter(RoutingParameter.portDirectionPenalty, 100)
    router.set_routing_option(RoutingOption.nudgeOrthogonalSegmentsConnectedToShapes, False)
    router.set_routing_option(RoutingOption.improveHyperedgeRoutesMovingJunctions, True)
    router.set_routing_option(RoutingOption.penaliseOrthogonalSharedPathsAtConnEnds, False)
    router.set_routing_option(RoutingOption.nudgeOrthogonalTouchingColinearSegments, False)
    poly1 = Polygon(4)
    poly1.set_point(0, Point(99, -20))
    poly1.set_point(1, Point(99, 0))
    poly1.set_point(2, Point(55, 0))
    poly1.set_point(3, Point(55, -20))
    ShapeRef(router, poly1, 1)
    poly2 = Polygon(4)
    poly2.set_point(0, Point(20, -65))
    poly2.set_point(1, Point(20, -45))
    poly2.set_point(2, Point(0, -45))
    poly2.set_point(3, Point(0, -65))
    ShapeRef(router, poly2, 2)
    poly3 = Polygon(4)
    poly3.set_point(0, Point(20, -90))
    poly3.set_point(1, Point(20, -70))
    poly3.set_point(2, Point(0, -70))
    poly3.set_point(3, Point(0, -90))
    ShapeRef(router, poly3, 3)
    poly4 = Polygon(4)
    poly4.set_point(0, Point(20, -115))
    poly4.set_point(1, Point(20, -95))
    poly4.set_point(2, Point(0, -95))
    poly4.set_point(3, Point(0, -115))
    ShapeRef(router, poly4, 4)
    poly5 = Polygon(4)
    poly5.set_point(0, Point(20, -140))
    poly5.set_point(1, Point(20, -120))
    poly5.set_point(2, Point(0, -120))
    poly5.set_point(3, Point(0, -140))
    ShapeRef(router, poly5, 5)
    poly6 = Polygon(4)
    poly6.set_point(0, Point(75, -185))
    poly6.set_point(1, Point(75, -165))
    poly6.set_point(2, Point(55, -165))
    poly6.set_point(3, Point(55, -185))
    ShapeRef(router, poly6, 6)
    poly7 = Polygon(4)
    poly7.set_point(0, Point(100, -185))
    poly7.set_point(1, Point(100, -165))
    poly7.set_point(2, Point(80, -165))
    poly7.set_point(3, Point(80, -185))
    ShapeRef(router, poly7, 7)
    poly8 = Polygon(4)
    poly8.set_point(0, Point(125, -185))
    poly8.set_point(1, Point(125, -165))
    poly8.set_point(2, Point(105, -165))
    poly8.set_point(3, Point(105, -185))
    ShapeRef(router, poly8, 8)
    poly9 = Polygon(4)
    poly9.set_point(0, Point(150, -185))
    poly9.set_point(1, Point(150, -165))
    poly9.set_point(2, Point(130, -165))
    poly9.set_point(3, Point(130, -185))
    ShapeRef(router, poly9, 9)
    poly10 = Polygon(4)
    poly10.set_point(0, Point(175, -185))
    poly10.set_point(1, Point(175, -165))
    poly10.set_point(2, Point(155, -165))
    poly10.set_point(3, Point(155, -185))
    ShapeRef(router, poly10, 10)
    conn_ref11 = ConnRef(router, 11)
    src_pt11 = ConnEnd(Point(20, -47), 15)
    conn_ref11.set_source_endpoint(src_pt11)
    dst_pt11 = ConnEnd(Point(57, -165), 15)
    conn_ref11.set_dest_endpoint(dst_pt11)
    conn_ref11.set_routing_type(ConnType.Orthogonal)
    conn_ref12 = ConnRef(router, 12)
    src_pt12 = ConnEnd(Point(61, -165), 15)
    conn_ref12.set_source_endpoint(src_pt12)
    dst_pt12 = ConnEnd(Point(57, -20), 15)
    conn_ref12.set_dest_endpoint(dst_pt12)
    conn_ref12.set_routing_type(ConnType.Orthogonal)
    conn_ref13 = ConnRef(router, 13)
    src_pt13 = ConnEnd(Point(15, -74), 15)
    conn_ref13.set_source_endpoint(src_pt13)
    dst_pt13 = ConnEnd(Point(65, -20), 15)
    conn_ref13.set_dest_endpoint(dst_pt13)
    conn_ref13.set_routing_type(ConnType.Orthogonal)
    conn_ref14 = ConnRef(router, 14)
    src_pt14 = ConnEnd(Point(61, -20), 15)
    conn_ref14.set_source_endpoint(src_pt14)
    dst_pt14 = ConnEnd(Point(61, -24), 15)
    conn_ref14.set_dest_endpoint(dst_pt14)
    conn_ref14.set_routing_type(ConnType.Orthogonal)
    router.process_transaction()
    overlap = router.exists_orthogonal_fixed_segment_overlap()

    assert not (overlap)
