"""Translation of upstream ``cola/libavoid/tests/finalSegmentNudging2.cpp``.

Auto-generated by ``scripts/translate_upstream.py`` from
``vendor/adaptagrams/cola/libavoid/tests/finalSegmentNudging2.cpp`` at the commit
pinned by ``vendor/adaptagrams``. Regenerate rather than hand-edit.

Pass/fail signal mirrors upstream: exists_orthogonal_fixed_segment_overlap() must be False.
"""

from libavoid_py import (
    ConnDirFlag,
    ConnEnd,
    ConnRef,
    ConnType,
    JunctionRef,
    Point,
    Polygon,
    Rectangle,
    Router,
    RouterFlag,
    RoutingOption,
    RoutingParameter,
    ShapeRef,
)


def test_final_segment_nudging2() -> None:

    router = Router(RouterFlag.PolyLineRouting | RouterFlag.OrthogonalRouting)
    router.set_routing_penalty(RoutingParameter.segmentPenalty, 50)
    router.set_routing_penalty(RoutingParameter.anglePenalty, 0)
    router.set_routing_penalty(RoutingParameter.crossingPenalty, 0)
    router.set_routing_penalty(RoutingParameter.clusterCrossingPenalty, 4000)
    router.set_routing_penalty(RoutingParameter.fixedSharedPathPenalty, 0)
    router.set_routing_penalty(RoutingParameter.portDirectionPenalty, 100)
    router.set_routing_option(RoutingOption.nudgeOrthogonalSegmentsConnectedToShapes, True)
    router.set_routing_option(RoutingOption.improveHyperedgeRoutesMovingJunctions, True)
    router.set_routing_option(RoutingOption.penaliseOrthogonalSharedPathsAtConnEnds, False)
    poly3 = Polygon(4)
    poly3.set_point(0, Point(328, 368))
    poly3.set_point(1, Point(328, 400))
    poly3.set_point(2, Point(308, 400))
    poly3.set_point(3, Point(308, 368))
    ShapeRef(router, poly3, 3)
    poly4 = Polygon(4)
    poly4.set_point(0, Point(328, 492))
    poly4.set_point(1, Point(328, 524))
    poly4.set_point(2, Point(308, 524))
    poly4.set_point(3, Point(308, 492))
    ShapeRef(router, poly4, 4)
    poly13 = Polygon(4)
    poly13.set_point(0, Point(349, 415))
    poly13.set_point(1, Point(349, 477))
    poly13.set_point(2, Point(287, 477))
    poly13.set_point(3, Point(287, 415))
    ShapeRef(router, poly13, 13)
    poly17 = Polygon(4)
    poly17.set_point(0, Point(640.857, 336))
    poly17.set_point(1, Point(640.857, 398))
    poly17.set_point(2, Point(578.857, 398))
    poly17.set_point(3, Point(578.857, 336))
    ShapeRef(router, poly17, 17)
    poly18 = Polygon(4)
    poly18.set_point(0, Point(404, 364))
    poly18.set_point(1, Point(404, 404))
    poly18.set_point(2, Point(328, 404))
    poly18.set_point(3, Point(328, 364))
    ShapeRef(router, poly18, 18)
    poly19 = Polygon(4)
    poly19.set_point(0, Point(404, 488))
    poly19.set_point(1, Point(404, 528))
    poly19.set_point(2, Point(328, 528))
    poly19.set_point(3, Point(328, 488))
    ShapeRef(router, poly19, 19)
    poly26 = Polygon(4)
    poly26.set_point(0, Point(632.857, 419.5))
    poly26.set_point(1, Point(632.857, 459.5))
    poly26.set_point(2, Point(572.857, 459.5))
    poly26.set_point(3, Point(572.857, 419.5))
    ShapeRef(router, poly26, 26)
    conn_ref30 = ConnRef(router, 30)
    src_pt30 = ConnEnd(Point(318, 523), 2)
    conn_ref30.set_source_endpoint(src_pt30)
    dst_pt30 = ConnEnd(Point(609.857, 367), 15)
    conn_ref30.set_dest_endpoint(dst_pt30)
    conn_ref30.set_routing_type(ConnType.Orthogonal)
    conn_ref46 = ConnRef(router, 46)
    src_pt46 = ConnEnd(Point(609.857, 367), 15)
    conn_ref46.set_source_endpoint(src_pt46)
    dst_pt46 = ConnEnd(Point(318, 369), 1)
    conn_ref46.set_dest_endpoint(dst_pt46)
    conn_ref46.set_routing_type(ConnType.Orthogonal)
    conn_ref50 = ConnRef(router, 50)
    src_pt50 = ConnEnd(Point(609.857, 367), 15)
    conn_ref50.set_source_endpoint(src_pt50)
    dst_pt50 = ConnEnd(Point(577.857, 439.5), 4)
    conn_ref50.set_dest_endpoint(dst_pt50)
    conn_ref50.set_routing_type(ConnType.Orthogonal)
    router.process_transaction()
    at_ends = True
    overlap = router.exists_orthogonal_fixed_segment_overlap(at_ends)

    assert not (overlap)
