"""Translation of upstream ``cola/libavoid/tests/inlineOverlap10.cpp``.

Auto-generated by ``scripts/translate_upstream.py`` from
``vendor/adaptagrams/cola/libavoid/tests/inlineOverlap10.cpp`` at the commit
pinned by ``vendor/adaptagrams``. Regenerate rather than hand-edit.

Pass/fail signal mirrors upstream: exists_orthogonal_fixed_segment_overlap() must be False.
"""

from libavoid_py import (
    ATTACH_POS_BOTTOM,
    ATTACH_POS_CENTRE,
    ATTACH_POS_LEFT,
    ATTACH_POS_RIGHT,
    ATTACH_POS_TOP,
    CONNECTIONPIN_CENTRE,
    CONNECTIONPIN_UNSET,
    ConnDirFlag,
    ConnEnd,
    ConnRef,
    ConnType,
    JunctionRef,
    Point,
    Polygon,
    Rectangle,
    Router,
    RouterFlag,
    RoutingOption,
    RoutingParameter,
    ShapeConnectionPin,
    ShapeRef,
)


def test_inline_overlap10() -> None:

    router = Router(RouterFlag.OrthogonalRouting)
    router.set_routing_parameter(RoutingParameter.segmentPenalty, 50)
    router.set_routing_parameter(RoutingParameter.anglePenalty, 0)
    router.set_routing_parameter(RoutingParameter.crossingPenalty, 200)
    router.set_routing_parameter(RoutingParameter.clusterCrossingPenalty, 4000)
    router.set_routing_parameter(RoutingParameter.fixedSharedPathPenalty, 20000)
    router.set_routing_parameter(RoutingParameter.portDirectionPenalty, 100)
    router.set_routing_parameter(RoutingParameter.shapeBufferDistance, 0)
    router.set_routing_parameter(RoutingParameter.idealNudgingDistance, 25)
    router.set_routing_option(RoutingOption.nudgeOrthogonalSegmentsConnectedToShapes, False)
    router.set_routing_option(RoutingOption.improveHyperedgeRoutesMovingJunctions, True)
    router.set_routing_option(RoutingOption.penaliseOrthogonalSharedPathsAtConnEnds, True)
    router.set_routing_option(RoutingOption.nudgeOrthogonalTouchingColinearSegments, False)
    router.set_routing_option(RoutingOption.performUnifyingNudgingPreprocessingStep, True)
    router.set_routing_option(RoutingOption.improveHyperedgeRoutesMovingAddingAndDeletingJunctions, True)
    polygon = Polygon()
    conn_ref = None
    src_pt = ConnEnd()
    dst_pt = ConnEnd()
    new_route = Polygon()
    polygon = Polygon(4)
    polygon.set_point(0, Point(51000, 50740))
    polygon.set_point(1, Point(51000, 51135))
    polygon.set_point(2, Point(50650, 51135))
    polygon.set_point(3, Point(50650, 50740))
    shape_ref320077872 = ShapeRef(router, polygon, 320077872)
    ShapeConnectionPin(shape_ref320077872, 1, 0, 0.21519, True, 10, 4)
    ShapeConnectionPin(shape_ref320077872, 2, 1, 0.21519, True, 10, 8)
    ShapeConnectionPin(shape_ref320077872, 3, 0.0714286, 0.405063, True, 10, 4)
    ShapeConnectionPin(shape_ref320077872, 4, 1, 0.405063, True, 10, 8)
    ShapeConnectionPin(shape_ref320077872, 5, 0.0714286, 0.594937, True, 10, 4)
    ShapeConnectionPin(shape_ref320077872, 6, 1, 0.594937, True, 10, 8)
    ShapeConnectionPin(shape_ref320077872, 7, 0, 0.78481, True, 10, 4)
    ShapeConnectionPin(shape_ref320077872, 8, 1, 0.78481, True, 10, 8)
    polygon = Polygon(4)
    polygon.set_point(0, Point(51650, 50740))
    polygon.set_point(1, Point(51650, 51135))
    polygon.set_point(2, Point(51300, 51135))
    polygon.set_point(3, Point(51300, 50740))
    shape_ref346216920 = ShapeRef(router, polygon, 346216920)
    ShapeConnectionPin(shape_ref346216920, 1, 0, 0.21519, True, 10, 4)
    ShapeConnectionPin(shape_ref346216920, 2, 1, 0.21519, True, 10, 8)
    ShapeConnectionPin(shape_ref346216920, 3, 0, 0.405063, True, 10, 4)
    ShapeConnectionPin(shape_ref346216920, 4, 0.928571, 0.405063, True, 10, 8)
    ShapeConnectionPin(shape_ref346216920, 5, 0, 0.594937, True, 10, 4)
    ShapeConnectionPin(shape_ref346216920, 6, 0.928571, 0.594937, True, 10, 8)
    ShapeConnectionPin(shape_ref346216920, 7, 0, 0.78481, True, 10, 4)
    ShapeConnectionPin(shape_ref346216920, 8, 1, 0.78481, True, 10, 8)
    conn_ref = ConnRef(router, 13958908)
    src_pt = ConnEnd(shape_ref346216920, 3)
    conn_ref.set_source_endpoint(src_pt)
    dst_pt = ConnEnd(shape_ref320077872, 6)
    conn_ref.set_dest_endpoint(dst_pt)
    conn_ref.set_routing_type(ConnType.Orthogonal)
    conn_ref = ConnRef(router, 81482716)
    src_pt = ConnEnd(shape_ref320077872, 8)
    conn_ref.set_source_endpoint(src_pt)
    dst_pt = ConnEnd(shape_ref346216920, 7)
    conn_ref.set_dest_endpoint(dst_pt)
    conn_ref.set_routing_type(ConnType.Orthogonal)
    conn_ref = ConnRef(router, 180721992)
    src_pt = ConnEnd(shape_ref320077872, 4)
    conn_ref.set_source_endpoint(src_pt)
    dst_pt = ConnEnd(shape_ref346216920, 5)
    conn_ref.set_dest_endpoint(dst_pt)
    conn_ref.set_routing_type(ConnType.Orthogonal)
    conn_ref = ConnRef(router, 273666240)
    src_pt = ConnEnd(shape_ref320077872, 2)
    conn_ref.set_source_endpoint(src_pt)
    dst_pt = ConnEnd(shape_ref346216920, 1)
    conn_ref.set_dest_endpoint(dst_pt)
    conn_ref.set_routing_type(ConnType.Orthogonal)
    router.process_transaction()
    overlap = router.exists_orthogonal_fixed_segment_overlap()

    assert not (overlap)
