"""Translation of upstream ``cola/libavoid/tests/nudgeold.cpp``.

Auto-generated by ``scripts/translate_upstream.py`` from
``vendor/adaptagrams/cola/libavoid/tests/nudgeold.cpp`` at the commit
pinned by ``vendor/adaptagrams``. Regenerate rather than hand-edit.

Pass/fail signal mirrors upstream: process_transaction() must complete without raising.
"""

from libavoid_py import (
    ATTACH_POS_BOTTOM,
    ATTACH_POS_CENTRE,
    ATTACH_POS_LEFT,
    ATTACH_POS_RIGHT,
    ATTACH_POS_TOP,
    CONNECTIONPIN_CENTRE,
    CONNECTIONPIN_UNSET,
    ConnDirFlag,
    ConnEnd,
    ConnRef,
    ConnType,
    JunctionRef,
    Point,
    Polygon,
    Rectangle,
    Router,
    RouterFlag,
    RoutingOption,
    RoutingParameter,
    ShapeConnectionPin,
    ShapeRef,
)


def test_nudgeold() -> None:

    router = Router(RouterFlag.PolyLineRouting | RouterFlag.OrthogonalRouting)
    router.set_routing_penalty(RoutingParameter.segmentPenalty, 50)
    router.set_routing_penalty(RoutingParameter.anglePenalty, 0)
    router.set_routing_penalty(RoutingParameter.crossingPenalty, 0)
    router.set_routing_penalty(RoutingParameter.clusterCrossingPenalty, 4000)
    router.set_routing_penalty(RoutingParameter.fixedSharedPathPenalty, 110)
    router.set_routing_parameter(RoutingParameter.idealNudgingDistance, 25)
    poly426345871 = Polygon(4)
    poly426345871.set_point(0, Point(7200, 5240))
    poly426345871.set_point(1, Point(7200, 5660))
    poly426345871.set_point(2, Point(6690, 5660))
    poly426345871.set_point(3, Point(6690, 5240))
    ShapeRef(router, poly426345871, 426345871)
    poly596896212 = Polygon(4)
    poly596896212.set_point(0, Point(7200, 5740))
    poly596896212.set_point(1, Point(7200, 6160))
    poly596896212.set_point(2, Point(6690, 6160))
    poly596896212.set_point(3, Point(6690, 5740))
    ShapeRef(router, poly596896212, 596896212)
    conn_ref20026701 = ConnRef(router, 20026701)
    src_pt20026701 = ConnEnd(Point(7190, 5600), 8)
    conn_ref20026701.set_source_endpoint(src_pt20026701)
    dst_pt20026701 = ConnEnd(Point(7190, 5800), 8)
    conn_ref20026701.set_dest_endpoint(dst_pt20026701)
    conn_ref20026701.set_routing_type(ConnType.Orthogonal)
    conn_ref124776000 = ConnRef(router, 124776000)
    src_pt124776000 = ConnEnd(Point(7190, 5550), 8)
    conn_ref124776000.set_source_endpoint(src_pt124776000)
    dst_pt124776000 = ConnEnd(Point(7190, 5850), 8)
    conn_ref124776000.set_dest_endpoint(dst_pt124776000)
    conn_ref124776000.set_routing_type(ConnType.Orthogonal)
    conn_ref162425002 = ConnRef(router, 162425002)
    src_pt162425002 = ConnEnd(Point(7190, 5500), 8)
    conn_ref162425002.set_source_endpoint(src_pt162425002)
    dst_pt162425002 = ConnEnd(Point(7190, 5900), 8)
    conn_ref162425002.set_dest_endpoint(dst_pt162425002)
    conn_ref162425002.set_routing_type(ConnType.Orthogonal)
    conn_ref445102866 = ConnRef(router, 445102866)
    src_pt445102866 = ConnEnd(Point(7190, 5450), 8)
    conn_ref445102866.set_source_endpoint(src_pt445102866)
    dst_pt445102866 = ConnEnd(Point(7190, 5950), 8)
    conn_ref445102866.set_dest_endpoint(dst_pt445102866)
    conn_ref445102866.set_routing_type(ConnType.Orthogonal)
    conn_ref472520508 = ConnRef(router, 472520508)
    src_pt472520508 = ConnEnd(Point(7190, 5400), 8)
    conn_ref472520508.set_source_endpoint(src_pt472520508)
    dst_pt472520508 = ConnEnd(Point(7190, 6000), 8)
    conn_ref472520508.set_dest_endpoint(dst_pt472520508)
    conn_ref472520508.set_routing_type(ConnType.Orthogonal)
    conn_ref406587600 = ConnRef(router, 406587600)
    src_pt406587600 = ConnEnd(Point(7190, 5350), 8)
    conn_ref406587600.set_source_endpoint(src_pt406587600)
    dst_pt406587600 = ConnEnd(Point(7190, 6050), 8)
    conn_ref406587600.set_dest_endpoint(dst_pt406587600)
    conn_ref406587600.set_routing_type(ConnType.Orthogonal)
    conn_ref41657796 = ConnRef(router, 41657796)
    src_pt41657796 = ConnEnd(Point(7190, 5300), 8)
    conn_ref41657796.set_source_endpoint(src_pt41657796)
    dst_pt41657796 = ConnEnd(Point(7190, 6100), 8)
    conn_ref41657796.set_dest_endpoint(dst_pt41657796)
    conn_ref41657796.set_routing_type(ConnType.Orthogonal)
    router.process_transaction()
