"""libavoid-py — Python bindings for libavoid.

Phase 2 progressively exposes the routing surface. Phase 2 PR 1 adds
the geometry primitives (:class:`Point`, :class:`Box`, :class:`Polygon`,
:class:`Rectangle`, and the :data:`PolyLine` / :data:`Vector` aliases).
The :class:`Router`, :class:`ShapeRef`, and :class:`ConnRef` types land
in the PRs that follow.
"""

from ._core import (
    ATTACH_POS_BOTTOM,
    ATTACH_POS_CENTRE,
    ATTACH_POS_LEFT,
    ATTACH_POS_MAX_OFFSET,
    ATTACH_POS_MIN_OFFSET,
    ATTACH_POS_RIGHT,
    ATTACH_POS_TOP,
    CONNECTIONPIN_CENTRE,
    CONNECTIONPIN_UNSET,
    XDIM,
    YDIM,
    Box,
    ConnDirFlag,
    ConnEnd,
    ConnEndType,
    ConnRef,
    ConnType,
    JunctionRef,
    Point,
    Polygon,
    PolyLine,
    Rectangle,
    Router,
    RouterFlag,
    RoutingOption,
    RoutingParameter,
    ShapeConnectionPin,
    ShapeRef,
    Vector,
    chooseSensibleParamValue,
    version,
    zeroParamValue,
)

__all__ = [
    "ATTACH_POS_BOTTOM",
    "ATTACH_POS_CENTRE",
    "ATTACH_POS_LEFT",
    "ATTACH_POS_MAX_OFFSET",
    "ATTACH_POS_MIN_OFFSET",
    "ATTACH_POS_RIGHT",
    "ATTACH_POS_TOP",
    "CONNECTIONPIN_CENTRE",
    "CONNECTIONPIN_UNSET",
    "XDIM",
    "YDIM",
    "Box",
    "ConnDirFlag",
    "ConnEnd",
    "ConnEndType",
    "ConnRef",
    "ConnType",
    "JunctionRef",
    "Point",
    "PolyLine",
    "Polygon",
    "Rectangle",
    "Router",
    "RouterFlag",
    "RoutingOption",
    "RoutingParameter",
    "ShapeConnectionPin",
    "ShapeRef",
    "Vector",
    "chooseSensibleParamValue",
    "version",
    "zeroParamValue",
]
