from collections.abc import Iterator
from enum import IntEnum
from typing import overload

XDIM: int
YDIM: int

zeroParamValue: float
chooseSensibleParamValue: float

def version() -> str: ...

class Point:
    x: float
    y: float
    id: int
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: float, y: float) -> None: ...
    def equals(self, other: Point, epsilon: float = 0.0001) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: Point) -> bool: ...
    def __add__(self, other: Point) -> Point: ...
    def __sub__(self, other: Point) -> Point: ...
    def __getitem__(self, dim: int) -> float: ...
    def __setitem__(self, dim: int, value: float) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[float]: ...
    def __repr__(self) -> str: ...

Vector = Point

class Box:
    min: Point
    max: Point
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, min: Point, max: Point) -> None: ...
    def width(self) -> float: ...
    def height(self) -> float: ...
    def __repr__(self) -> str: ...

class Polygon:
    id: int
    ps: list[Point]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, n: int) -> None: ...
    def empty(self) -> bool: ...
    def size(self) -> int: ...
    def at(self, index: int) -> Point: ...
    def set_point(self, index: int, point: Point) -> None: ...
    def clear(self) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Point: ...
    def __iter__(self) -> Iterator[Point]: ...
    def __repr__(self) -> str: ...

PolyLine = Polygon

class Rectangle(Polygon):
    @overload
    def __init__(self, top_left: Point, bottom_right: Point) -> None: ...
    @overload
    def __init__(self, centre: Point, width: float, height: float) -> None: ...

class RouterFlag(IntEnum):
    PolyLineRouting = 1
    OrthogonalRouting = 2

class RoutingParameter(IntEnum):
    segmentPenalty = 0
    anglePenalty = 1
    crossingPenalty = 2
    clusterCrossingPenalty = 3
    fixedSharedPathPenalty = 4
    portDirectionPenalty = 5
    shapeBufferDistance = 6
    idealNudgingDistance = 7
    reverseDirectionPenalty = 8

class RoutingOption(IntEnum):
    nudgeOrthogonalSegmentsConnectedToShapes = 0
    improveHyperedgeRoutesMovingJunctions = 1
    penaliseOrthogonalSharedPathsAtConnEnds = 2
    nudgeOrthogonalTouchingColinearSegments = 3
    performUnifyingNudgingPreprocessingStep = 4
    improveHyperedgeRoutesMovingAddingAndDeletingJunctions = 5
    nudgeSharedPathsWithCommonEndPoint = 6

class Router:
    def __init__(self, flags: int) -> None: ...
    def process_transaction(self) -> bool: ...
    def set_transaction_use(self, use: bool) -> None: ...
    def transaction_use(self) -> bool: ...
    def set_routing_parameter(
        self, parameter: RoutingParameter, value: float = ...
    ) -> None: ...
    def routing_parameter(self, parameter: RoutingParameter) -> float: ...
    def set_routing_option(self, option: RoutingOption, value: bool) -> None: ...
    def routing_option(self, option: RoutingOption) -> bool: ...
    def set_routing_penalty(
        self, parameter: RoutingParameter, value: float = ...
    ) -> None: ...
    def exists_invalid_orthogonal_paths(self) -> bool: ...
    def delete_shape(self, shape: ShapeRef) -> None: ...
    @overload
    def move_shape(self, shape: ShapeRef, new_polygon: Polygon) -> None: ...
    @overload
    def move_shape(self, shape: ShapeRef, dx: float, dy: float) -> None: ...
    def output_diagram(self, name: str = "") -> None: ...

class ShapeRef:
    def __init__(self, router: Router, polygon: Polygon, id: int = 0) -> None: ...
    def id(self) -> int: ...
    def polygon(self) -> Polygon: ...
    def position(self) -> Point: ...
    def routing_box(self) -> Box: ...
    def routing_polygon(self) -> Polygon: ...
    def set_new_poly(self, polygon: Polygon) -> None: ...
