from collections.abc import Iterator
from typing import overload

XDIM: int
YDIM: int

def version() -> str: ...

class Point:
    x: float
    y: float
    id: int
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, x: float, y: float) -> None: ...
    def equals(self, other: Point, epsilon: float = 0.0001) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: Point) -> bool: ...
    def __add__(self, other: Point) -> Point: ...
    def __sub__(self, other: Point) -> Point: ...
    def __getitem__(self, dim: int) -> float: ...
    def __setitem__(self, dim: int, value: float) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[float]: ...
    def __repr__(self) -> str: ...

Vector = Point

class Box:
    min: Point
    max: Point
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, min: Point, max: Point) -> None: ...
    def width(self) -> float: ...
    def height(self) -> float: ...
    def __repr__(self) -> str: ...

class Polygon:
    id: int
    ps: list[Point]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, n: int) -> None: ...
    def empty(self) -> bool: ...
    def size(self) -> int: ...
    def at(self, index: int) -> Point: ...
    def set_point(self, index: int, point: Point) -> None: ...
    def clear(self) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Point: ...
    def __iter__(self) -> Iterator[Point]: ...
    def __repr__(self) -> str: ...

PolyLine = Polygon

class Rectangle(Polygon):
    @overload
    def __init__(self, top_left: Point, bottom_right: Point) -> None: ...
    @overload
    def __init__(self, centre: Point, width: float, height: float) -> None: ...
